export const REQUEST_CATEGORY = 'REQUEST_CATEGORY'
export const ON_CATEGORY_SUCCESS = 'ON_CATEGORY_SUCCESS'
export const ON_CATEGORY_FAILURE = 'ON_CATEGORY_FAILURE'

export const REQUEST_IMAGES = 'REQUEST_IMAGES'
export const ON_IMAGES_SUCCESS = 'ON_IMAGES_SUCCESS'
export const ON_IMAGES_FAILURE = 'ON_IMAGES_FAILURE'